name: deploy docs

on:
  push: 
    branches:
      - main
  
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - run: npm ci

      - run: npm run build
        env: 
          TURBO_TOKEN: uzaQ16Ozt7XC5e2D4iYEYW1Y
          TURBO_TEAM: gmd-ev

      - name: Deploy storybook
        working-directory: ./packages/docs
        run: npm run deploy-storybook -- --branch=main --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
